# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-msbuild@v1
      with:
        dotnet-version: 8.0.x

    - name: Setup NuGet
      uses: NuGet/setup-nuget@1.0.2
      
    - name: Restore NuGet
      run: nuget restore FiguresCalculation.sln
      
    - name: Build
      run: msbuild FiguresCalculation.sln --configuration Release --no-restore
